image:
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - TOXENV: py39
      fast_finish: true
      PYTHON_V: "3.9"
      PYTHON: "C:\\Python39-x64"

stack: python %PYTHON_V%

install:
  - python --version
  - python -m pip install tox
  - python -m pip install -r requirements.txt
  # install wszst
  - curl https://szs.wiimm.de/download/szs-v2.24a-r8414-x86_64.tar.gz -o wszst.tar.gz
  - tar -xf wszst.tar.gz
  - cd szs*
  - export PATH=$PATH:$(pwd)/bin
  - echo $PATH
  - cd ..

build_script:
  - export PYTHONPATH=$(pwd):$(pwd)/abmatt/build
  - cd abmatt/build
  - echo $APPVEYOR_BUILD_VERSION
  - python build.py $APPVEYOR_BUILD_VERSION
  - cd ../..

test_script:
  - python -m tox -e $TOXENV

artifacts:
  - path: 'abmatt\dist\abmatt_*.tar.gz'
    name: Abmatt-tar

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    # install wszst
    - curl https://szs.wiimm.de/download/szs-v2.24a-r8414-cygwin64.zip -o wszst.zip
    - 7z x wszst.zip
    - cd szs*
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%;%CD%\bin
    - cd ..
    - python --version
    - python -m pip install tox
    - python -m pip install -r requirements.txt

  build_script:
    # NSIS
    - SET PYTHONPATH=%CD%;%CD%\abmatt\build
    - ps choco install nsis.install
    - set "PATH=%PATH%;C:\Program Files (x86)\NSIS"
    - curl -fsS https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -o plugin.zip
    - 7z x plugin.zip -o"C:\Program Files (x86)\NSIS"
    - cd abmatt/build
    - echo %APPVEYOR_BUILD_VERSION%
    - python build.py %APPVEYOR_BUILD_VERSION%
    - cd ../..

  test_script:
    - python -m tox -e %TOXENV%

  artifacts:
    - path: 'abmatt\dist\abmatt_*.zip'
      name: Abmatt-zip


deploy:
  release: ABMatt v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: EI0LiQ9R33njUgd776KqE7CypD07ckGhRixFjMjhWEAKSRecHBDM69OairVM8Qik
  artifact: Abmatt-zip Abmatt-tar
  draft: true
  prerelease: false
  on:
    branch:
      - release
      - master